#!/bin/sh

xwallpaper --center ~/Pictures/tux.jpg

if [ -f "$XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ];then
	. "$XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi

exec dwm
